apiVersion: apps/v1
kind: Deployment
metadata:
  name: ey-cart-dp
  namespace: pavitra-ns
  labels:
    app: cart
spec: # It defines the behaviour of the replicaset
  replicas: 3
  selector: 
    matchLabels:
      app: web
  template: # this is pod defination
    metadata:
      labels:
        app: web
    spec: # It contains container defination
      containers:
        - name: ey-cart-container
          image: muralisocial123/flipkart-app-web:v1.1.0
          ports:
            - containerPort: 80