apiVersion: v1
kind: Pod
metadata:
  name: recuitment
  namespace: recuitment_app-ns
  labels:
    app: recuitment-app
spec:
  containers:
    - name: recuitment-container
      image: pavithrasambath2003/recuitment:latest
      ports:
        - containerPort: 3000